# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-14 05:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=250)),
                ('blood_group', models.CharField(max_length=10)),
                ('district', models.CharField(max_length=50)),
                ('date', models.DateField(null=True)),
                ('contact_number', models.CharField(max_length=50)),
                ('isDeleted', models.BooleanField(default=False)),
            ],
        ),
    ]
