# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-16 15:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloodBank', '0003_donor_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blood_group_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_group', models.CharField(max_length=50)),
                ('donor_counter', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='District_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district_name', models.CharField(max_length=100)),
                ('donor_counter', models.IntegerField(default=0)),
            ],
        ),
    ]
