# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-16 16:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bloodBank', '0004_blood_group_info_district_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donor',
            name='name',
        ),
    ]
